Banking_System_Client: LoginWidget Class Reference
LoginWidget Class Reference
The LoginWidget class provides a user interface for logging into the banking system.
#include <loginwidget.h>
Public Slots
void onConnected ()
Slot to handle successful connection to the server.
void onDisconnected ()
Slot to handle disconnection from the server.
void onFailedRequest (QString message)
Slot to handle failed login request.
void onSuccessfullRequest (QString message)
Slot to handle successful login request.
void clearFields ()
Clears the input fields for email and password.
Signals
void connectToServer (const QString &host, quint16 port)
Signal emitted to connect to the server.
void disconnectFromServer ()
Signal emitted to disconnect from the server.
void sendLoginRequest (QJsonObject loginData)
Signal emitted to send login request.
Public Member Functions
LoginWidget (QWidget *parent=nullptr)
Constructs a LoginWidget instance.
Detailed Description
The LoginWidget class provides a user interface for logging into the banking system.
The LoginWidget is responsible for user authentication, including connecting to the server, handling user input, and displaying appropriate feedback. It provides fields for email and password entry, a login button, and an indicator for connection status.
Constructor & Destructor Documentation
LoginWidget()
LoginWidget::LoginWidget (QWidget * parent = nullptr) explicit
Constructs a LoginWidget instance.
Parameters
parent The parent QWidget, defaults to nullptr.
Member Function Documentation
connectToServer
void LoginWidget::connectToServer (const QString & host, quint16 port) signal
Signal emitted to connect to the server.
Parameters
host The server IP address.
port The server port.
Referenced by UIManager::createLoginWidget().
onFailedRequest
void LoginWidget::onFailedRequest (QString message) slot
Slot to handle failed login request.
Parameters
message The error message to display.
Referenced by onDisconnected(), and UIManager::onFailedNotification().
onSuccessfullRequest
void LoginWidget::onSuccessfullRequest (QString message) slot
Slot to handle successful login request.
Parameters
message The success message to display.
Referenced by onConnected(), and UIManager::onSuccessfullNotification().
sendLoginRequest
void LoginWidget::sendLoginRequest (QJsonObject loginData) signal
Signal emitted to send login request.
Parameters
loginData The JSON object containing login data.
Referenced by UIManager::createLoginWidget().
The documentation for this class was generated from the following files:
loginwidget.h
loginwidget.cpp