Banking_System_Client: UIManager Class Reference
UIManager Class Reference
Public Slots
void responseReady (QJsonObject Data)
Slot to handle responses from the server.
void requestReady (QJsonObject Data)
Slot to handle requests that are ready to be sent.
void logout ()
Logs out the current user.
void createLoginWidget ()
Creates the login widget.
void createAdminWidget (QString email, QString first_name)
Creates the admin widget.
void createUserWidget (QString email, QString first_name, QString account_number, QString balance)
Creates the user widget.
void onSuccessfullNotification (QString message)
Displays a successful notification.
void onFailedNotification (QString message)
Displays a failed notification.
void closeAdminWidget ()
Closes the admin widget.
void closeUserWidget ()
Closes the user widget.
void closeLoginWidget ()
Closes the login widget.
void connectToTheServer (const QString &host, quint16 port)
Connects to the server.
void disconnectFromTheServer ()
Disconnects from the server.
void onConnectionResponse (bool status)
Handles the server connection response.
Signals
void makeRequest (QJsonObject Data)
Signal emitted when a request is ready to be sent to the server.
void requestConnection (const QString &host, quint16 port)
Signal emitted to request a connection to the server.
void requestDisconnection ()
Signal emitted to request a disconnection from the server.
Public Member Functions
~UIManager ()
Destructor for the UIManager class.
UIManager (const UIManager &)=delete
Deleted copy constructor to prevent copying.
void operator= (const UIManager &)=delete
Deleted assignment operator to prevent copying.
Static Public Member Functions
static UIManager * getInstance (QObject *parent=nullptr)
Gets the singleton instance of UIManager.
Constructor & Destructor Documentation
~UIManager()
UIManager::~UIManager ()
Destructor for the UIManager class.
Cleans up the main window and its widgets.
Member Function Documentation
connectToTheServer
void UIManager::connectToTheServer (const QString & host, quint16 port) slot
Connects to the server.
Parameters
host Server host address.
port Server port number.
Referenced by createLoginWidget().
createAdminWidget
void UIManager::createAdminWidget (QString email, QString first_name) slot
Creates the admin widget.
Parameters
email Admin email address.
first_name Admin first name.
createLoginWidget
void UIManager::createLoginWidget () slot
Creates the login widget.
Initializes and displays the login widget.
createUserWidget
void UIManager::createUserWidget (QString email, QString first_name, QString account_number, QString balance) slot
Creates the user widget.
Parameters
email User email address.
first_name User first name.
account_number User account number.
balance User account balance.
getInstance()
UIManager * UIManager::getInstance (QObject * parent = nullptr) static
Gets the singleton instance of UIManager.
Parameters
parent Optional parent QObject.
Returns
Pointer to the UIManager instance.
logout
void UIManager::logout () slot
Logs out the current user.
Disconnects signals and resets the UI to the login widget.
Referenced by closeAdminWidget(), closeUserWidget(), createAdminWidget(), and createUserWidget().
makeRequest
void UIManager::makeRequest (QJsonObject Data) signal
Signal emitted when a request is ready to be sent to the server.
Parameters
Data JSON object containing the request data.
Referenced by requestReady().
onConnectionResponse
void UIManager::onConnectionResponse (bool status) slot
Handles the server connection response.
Parameters
status Connection status (true if connected, false otherwise).
onFailedNotification
void UIManager::onFailedNotification (QString message) slot
Displays a failed notification.
Parameters
message The failure message to be displayed.
onSuccessfullNotification
void UIManager::onSuccessfullNotification (QString message) slot
Displays a successful notification.
Parameters
message The success message to be displayed.
requestConnection
void UIManager::requestConnection (const QString & host, quint16 port) signal
Signal emitted to request a connection to the server.
Parameters
host Server host address.
port Server port number.
Referenced by connectToTheServer().
requestReady
void UIManager::requestReady (QJsonObject Data) slot
Slot to handle requests that are ready to be sent.
Parameters
Data JSON object containing the request data.
Referenced by createLoginWidget().
responseReady
void UIManager::responseReady (QJsonObject Data) slot
Slot to handle responses from the server.
Parameters
Data JSON object containing the response data.
The documentation for this class was generated from the following files:
UIManager.h
UIManager.cpp