Banking_System_Client: UserWidget Class Reference
UserWidget Class Reference
The UserWidget class provides a user interface for managing user accounts, performing transactions, and modifying settings within the banking application.
#include <UserWidget.h>
Public Slots
void onTransactionsFetched (const QList< QMap< QString, QString > > &transactions)
Slot to handle successful fetch of transactions.
void onBalanceFetched (const QString balance)
Slot to handle successful fetch of balance.
void onSuccessfullRequest (QString message)
Slot to handle successful request.
void onFailedRequest (QString message)
Slot to handle failed request.
Signals
void logout ()
Emitted when the user requests to log out.
Public Member Functions
UserWidget (QString email, QString first_name, QString account_number, QString balance, QWidget *parent=nullptr)
Constructs a UserWidget instance.
Detailed Description
The UserWidget class provides a user interface for managing user accounts, performing transactions, and modifying settings within the banking application.
This class represents the main user interface component that allows users to interact with their account information, view transaction history, perform transfers, and update personal settings. It includes several tabs for different functionalities such as Home, Transfer, and Settings.
The UserWidget class manages the display of user data, handles user interactions, and communicates with the backend server through the RequestManager. It provides features for viewing transaction history, performing money transfers, updating account details, and logging out of the application.
The widget consists of:
Home tab: Displays welcome message, current balance, and transaction history.
Transfer tab: Allows users to transfer funds to another account or email.
Settings tab: Provides options to update email, update password, and log out.
Constructor & Destructor Documentation
UserWidget()
UserWidget::UserWidget (QString email, QString first_name, QString account_number, QString balance, QWidget * parent = nullptr)
Constructs a UserWidget instance.
Parameters
email The user's email address.
first_name The user's first name.
account_number The user's account number.
balance The user's current balance.
parent The parent widget (optional).
Member Function Documentation
onBalanceFetched
void UserWidget::onBalanceFetched (const QString balance) slot
Slot to handle successful fetch of balance.
Parameters
balance The balance fetched from the server.
Referenced by UIManager::closeUserWidget(), UIManager::createUserWidget(), and UserWidget().
onFailedRequest
void UserWidget::onFailedRequest (QString message) slot
Slot to handle failed request.
Parameters
message The failure message to display.
Referenced by UIManager::onFailedNotification().
onSuccessfullRequest
void UserWidget::onSuccessfullRequest (QString message) slot
Slot to handle successful request.
Parameters
message The success message to display.
Referenced by onBalanceFetched(), UIManager::onSuccessfullNotification(), and onTransactionsFetched().
onTransactionsFetched
void UserWidget::onTransactionsFetched (const QList< QMap< QString, QString > > & transactions) slot
Slot to handle successful fetch of transactions.
Parameters
transactions The list of transactions fetched from the server.
Referenced by UIManager::closeUserWidget(), and UIManager::createUserWidget().
The documentation for this class was generated from the following files:
UserWidget.h
UserWidget.cpp