Banking_System_Client: IValidationStrategy Class Reference
IValidationStrategy Class Reference abstract
Interface for validation strategies.
#include <ValidationStrategy.h>
Public Member Functions
virtual bool isValid (const QString &input) const =0
Validates the input string.
virtual QString errorMessage () const =0
Retrieves the error message for invalid input.
Detailed Description
Interface for validation strategies.
Provides a common interface for different validation strategies to validate input data.
Member Function Documentation
errorMessage()
virtual QString IValidationStrategy::errorMessage () const pure virtual
Retrieves the error message for invalid input.
Returns
The error message as a QString.
Implemented in NameValidationStrategy, EmailValidationStrategy, PasswordValidationStrategy, BalanceValidationStrategy, and AccountNumberValidationStrategy.
Referenced by BaseDialog::validateInput().
isValid()
virtual bool IValidationStrategy::isValid (const QString & input) const pure virtual
Validates the input string.
Parameters
input The input string to validate.
Returns
True if the input is valid, otherwise false.
Implemented in NameValidationStrategy, EmailValidationStrategy, PasswordValidationStrategy, BalanceValidationStrategy, and AccountNumberValidationStrategy.
Referenced by BaseDialog::updateConfirmButtonState(), and BaseDialog::validateInput().
The documentation for this class was generated from the following file:
ValidationStrategy.h