Banking_System_Client: ClientHandler Class Reference
ClientHandler Class Reference
A class for managing client requests and responses.
#include <ClientHandler.h>
Public Slots
void sendRequest (QJsonObject request)
Sends a request to the server.
void onResponseReady (QByteArray response)
Slot to handle the response received from the server.
void requestClientConnection (const QString &host, quint16 port)
Requests a connection to the server.
void requestClientDisconnection ()
Requests disconnection from the server.
void onConnectedSignal ()
Slot to handle the connected signal.
void onDisconnectedSignal ()
Slot to handle the disconnected signal.
Signals
void sendResponseBack (QJsonObject response)
Signal to send the response back to the window manager.
Public Member Functions
ClientHandler (QObject *parent=nullptr)
Constructor for ClientHandler.
~ClientHandler ()
Destructor for ClientHandler.
void run ()
Runs the event loop for the ClientHandler.
Detailed Description
A class for managing client requests and responses.
The ClientHandler class handles the client-side operations such as sending requests, receiving responses, and managing connections. It uses the TcpClient class to handle the actual TCP communication.
Constructor & Destructor Documentation
ClientHandler()
ClientHandler::ClientHandler (QObject * parent = nullptr) explicit
Constructor for ClientHandler.
Parameters
parent The parent QObject, default is nullptr.
Member Function Documentation
onResponseReady
void ClientHandler::onResponseReady (QByteArray response) slot
Slot to handle the response received from the server.
Parameters
response The response data in QByteArray format.
Referenced by run().
requestClientConnection
void ClientHandler::requestClientConnection (const QString & host, quint16 port) slot
Requests a connection to the server.
Parameters
host The server host.
port The server port.
sendRequest
void ClientHandler::sendRequest (QJsonObject request) slot
Sends a request to the server.
Parameters
request The JSON object containing the request data.
sendResponseBack
void ClientHandler::sendResponseBack (QJsonObject response) signal
Signal to send the response back to the window manager.
Parameters
response The JSON object containing the response data.
Referenced by onConnectedSignal(), onDisconnectedSignal(), and onResponseReady().
The documentation for this class was generated from the following files:
ClientHandler.h
ClientHandler.cpp