Banking_System_Client: TcpClient Class Reference
TcpClient Class Reference
A class for managing TCP client connections.
#include <tcpclient.h>
Signals
void ResponseReadySignal (QByteArray response)
Signal emitted when a response is ready.
void ConnectedSignal ()
Signal emitted when connected to the server.
void DisconnectedSignal ()
Signal emitted when disconnected from the server.
Public Member Functions
TcpClient (QObject *parent=nullptr)
Constructor for TcpClient.
~TcpClient ()
Destructor for TcpClient.
void connectToServer (const QString &host, quint16 port)
Connect to a TCP server.
void sendTcpRequest (const QByteArray &request)
Send a TCP request.
void closeConnection ()
Close the TCP connection.
Detailed Description
A class for managing TCP client connections.
The TcpClient class is responsible for establishing a connection to a TCP server, sending requests, receiving responses, and handling various socket states and errors. It provides signals for connection status and incoming responses.
Constructor & Destructor Documentation
TcpClient()
TcpClient::TcpClient (QObject * parent = nullptr) explicit
Constructor for TcpClient.
Parameters
parent The parent object.
Initializes the TcpClient object and connects the necessary signals and slots.
~TcpClient()
TcpClient::~TcpClient ()
Destructor for TcpClient.
Cleans up the TcpClient object, ensuring the socket is properly deleted.
Member Function Documentation
closeConnection()
void TcpClient::closeConnection ()
Close the TCP connection.
Closes the connection to the server if it is open.
Referenced by ClientHandler::requestClientDisconnection().
connectToServer()
void TcpClient::connectToServer (const QString & host, quint16 port)
Connect to a TCP server.
Parameters
host The host address of the server.
port The port number to connect to.
Initiates a connection to the specified server.
Referenced by ClientHandler::requestClientConnection().
ResponseReadySignal
void TcpClient::ResponseReadySignal (QByteArray response) signal
Signal emitted when a response is ready.
Parameters
response The response data received from the server.
Referenced by ClientHandler::run().
sendTcpRequest()
void TcpClient::sendTcpRequest (const QByteArray & request)
Send a TCP request.
Parameters
request The request data to be sent.
Sends the specified request to the connected server.
Referenced by ClientHandler::sendRequest().
The documentation for this class was generated from the following files:
tcpclient.h
tcpclient.cpp