BankingSystem_Client: BaseDialog Class Reference
BaseDialog Class Reference abstract
The BaseDialog class provides a base class for creating dialogs with validation support.
#include <BaseDialog.h>
Public Member Functions
BaseDialog (QWidget *parent=nullptr)
Constructor for BaseDialog.
virtual QVariantMap getData () const =0
Pure virtual function to get the data from the dialog.
Protected Member Functions
virtual void setupUI ()=0
Pure virtual function to set up the user interface.
virtual void connectSignals ()
Connects signals for the dialog.
QtMaterialTextField * createInputField (QVBoxLayout *layout, const QString &labelText, IValidationStrategy *validationStrategy, bool isPassword=false)
Creates an input field with validation.
void validateInput (QtMaterialTextField *field)
Validates the input of a specified field.
void updateConfirmButtonState ()
Updates the state of the confirm button based on the validity of the form.
void setFieldValidityStyle (QtMaterialTextField *field, QLabel *errorLabel, const QString &errorMessage, bool isValid)
Sets the validity style of an input field.
Protected Attributes
QMap< QtMaterialTextField *, IValidationStrategy * > validationStrategies_
Stores validation strategies for input fields.
QMap< QtMaterialTextField *, QLabel * > errorLabels_
Stores error labels for input fields.
QtMaterialFlatButton * confirmButton
The confirm button.
QtMaterialFlatButton * cancelButton
The cancel button.
Detailed Description
The BaseDialog class provides a base class for creating dialogs with validation support.
This class is responsible for setting up the user interface, connecting signals, and validating input fields.
Constructor & Destructor Documentation
BaseDialog()
BaseDialog::BaseDialog (QWidget * parent = nullptr)
Constructor for BaseDialog.
Parameters
parent The parent widget.
Member Function Documentation
createInputField()
QtMaterialTextField * BaseDialog::createInputField (QVBoxLayout * layout, const QString & labelText, IValidationStrategy * validationStrategy, bool isPassword = false) protected
Creates an input field with validation.
Parameters
layout The layout to add the input field to.
labelText The text for the label associated with the input field.
validationStrategy The validation strategy for the input field.
isPassword Boolean flag to indicate if the input field is for password input.
Returns
A pointer to the created input field.
Referenced by UpdateEmailDialog::setupUI(), and UpdatePasswordDialog::setupUI().
getData()
virtual QVariantMap BaseDialog::getData () const pure virtual
Pure virtual function to get the data from the dialog.
Returns
A QVariantMap containing the data.
Implemented in UpdateUserDialog, UpdatePasswordDialog, UpdateEmailDialog, and CreateUserDialog.
setFieldValidityStyle()
void BaseDialog::setFieldValidityStyle (QtMaterialTextField * field, QLabel * errorLabel, const QString & errorMessage, bool isValid) protected
Sets the validity style of an input field.
Parameters
field The input field to update.
errorLabel The label to display error messages.
errorMessage The error message to display.
isValid Boolean flag to indicate if the input is valid.
Referenced by validateInput().
validateInput()
void BaseDialog::validateInput (QtMaterialTextField * field) protected
Validates the input of a specified field.
Parameters
field The input field to validate.
Referenced by connectSignals().
The documentation for this class was generated from the following files:
BaseDialog.h
BaseDialog.cpp