Banking_System_Client: ResponseManager Class Reference
ResponseManager Class Reference
Manages the responses received from the server.
#include <ResponseManager.h>
Public Types
enum AvailableRequests {
Login = 1 , GetAccountnumber , GetBalance , GetTransactionsHistory ,
MakeTransaction , TransferAmount , GetDatabase , CreateNewUser ,
DeleteUser , UpdateUser , UserInit , UpdateEmail ,
UpdatePassword , JsonParseError = -1 , Connection = -2
}
Defines the types of requests that can be handled.
Signals
void userloginSuccess (QString email, QString first_name, QString account_number, QString balance)
Signal emitted when a user login is successful.
void adminLoginSuccess (QString email, QString first_name)
Signal emitted when an admin login is successful.
void ConnectionResponse (bool status)
Signal emitted for connection response.
void TransactionsFetched (const QList< QMap< QString, QString >> &transactions)
Signal emitted when transactions are fetched.
void DatabaseFetched (const QList< QMap< QString, QString >> &databaseContent)
Signal emitted when the database content is fetched.
void BalanceFetched (QString balance)
Signal emitted when the balance is fetched.
void SuccessfullRequest (QString message)
Signal emitted for a successful request.
void FailedRequest (QString message)
Signal emitted for a failed request.
Public Member Functions
bool getResponseStatus (QJsonObject Data)
Checks the status value in the response.
QString getResponseMessage (QJsonObject Data)
Retrieves the message from the response.
ResponseManager (QObject *parent=nullptr)
Constructor for ResponseManager.
void handleResponse (QJsonObject Data)
Handles the response received from the server.
Detailed Description
Manages the responses received from the server.
The ResponseManager class processes server responses and emits signals based on the response type. It handles various response types defined in the AvailableRequests enum and provides feedback through signals to update the application state accordingly.
Member Enumeration Documentation
AvailableRequests
enum ResponseManager::AvailableRequests
Defines the types of requests that can be handled.
Enumerator
Login
User login response.
GetAccountnumber
Response to get account number.
GetBalance
Response to get account balance.
GetTransactionsHistory
Response to get transaction history.
MakeTransaction
Response to make a transaction.
TransferAmount
Response to transfer an amount (not used for now)
GetDatabase
Response to get the database.
CreateNewUser
Response to create a new user.
DeleteUser
Response to delete a user.
UpdateUser
Response to update user information.
UserInit
Response to initialize user.
UpdateEmail
Response to update user email.
UpdatePassword
Response to update user password.
JsonParseError
Indicates a JSON parse error.
Connection
Indicates a connection response.
Constructor & Destructor Documentation
ResponseManager()
ResponseManager::ResponseManager (QObject * parent = nullptr) explicit
Constructor for ResponseManager.
Parameters
parent The parent QObject, default is nullptr.
Member Function Documentation
adminLoginSuccess
void ResponseManager::adminLoginSuccess (QString email, QString first_name) signal
Signal emitted when an admin login is successful.
Parameters
email Admin's email.
first_name Admin's first name.
Referenced by handleResponse().
BalanceFetched
void ResponseManager::BalanceFetched (QString balance) signal
Signal emitted when the balance is fetched.
Parameters
balance User's balance.
Referenced by UIManager::closeUserWidget(), UIManager::createUserWidget(), and handleResponse().
ConnectionResponse
void ResponseManager::ConnectionResponse (bool status) signal
Signal emitted for connection response.
Parameters
status Connection status (true for success, false for failure).
Referenced by handleResponse().
DatabaseFetched
void ResponseManager::DatabaseFetched (const QList< QMap< QString, QString >> & databaseContent) signal
Signal emitted when the database content is fetched.
Parameters
databaseContent List of database content.
Referenced by UIManager::closeAdminWidget(), UIManager::createAdminWidget(), and handleResponse().
FailedRequest
void ResponseManager::FailedRequest (QString message) signal
Signal emitted for a failed request.
Parameters
message Failure message.
Referenced by handleResponse().
getResponseMessage()
QString ResponseManager::getResponseMessage (QJsonObject Data)
Retrieves the message from the response.
Parameters
Data The QJsonObject representing the response data.
Returns
The message as a QString.
Referenced by handleResponse().
getResponseStatus()
bool ResponseManager::getResponseStatus (QJsonObject Data)
Checks the status value in the response.
Parameters
Data The QJsonObject representing the response data.
Returns
true if the status value is 1, false otherwise.
Referenced by handleResponse().
handleResponse()
void ResponseManager::handleResponse (QJsonObject Data)
Handles the response received from the server.
Parameters
Data The QJsonObject representing the response data.
Returns
void
Referenced by UIManager::responseReady().
SuccessfullRequest
void ResponseManager::SuccessfullRequest (QString message) signal
Signal emitted for a successful request.
Parameters
message Success message.
Referenced by handleResponse().
TransactionsFetched
void ResponseManager::TransactionsFetched (const QList< QMap< QString, QString >> & transactions) signal
Signal emitted when transactions are fetched.
Parameters
transactions List of transactions.
Referenced by UIManager::closeAdminWidget(), UIManager::closeUserWidget(), UIManager::createAdminWidget(), UIManager::createUserWidget(), and handleResponse().
userloginSuccess
void ResponseManager::userloginSuccess (QString email, QString first_name, QString account_number, QString balance) signal
Signal emitted when a user login is successful.
Parameters
email User's email.
first_name User's first name.
account_number User's account number.
balance User's balance.
Referenced by handleResponse().
The documentation for this class was generated from the following files:
ResponseManager.h
ResponseManager.cpp