#--------------------------------------------------------------------------------
# Workflow configuration
#--------------------------------------------------------------------------------

name: Build
on:
  push:               # Run on push
  pull_request:       # Run on pull-request


jobs:
  build-windows:
      runs-on: windows-latest
      steps:
        #
        # Checkout the repository
        #
        - name: Checkout repository and submodules
          uses: actions/checkout@v2
          with:
            submodules: recursive

        #
        # Configure MSVC
        #
        - name: Configure MSVC
          uses: ilammy/msvc-dev-cmd@v1
          with:
            arch: x64
            spectre: true

        #
        # Install Qt
        #
        - name: Install Qt
          uses: jurplel/install-qt-action@v2
          with:
            aqtversion: '==3.1.*'
            version: '6.7.1'
            host: 'windows'
            target: 'desktop'
            arch: 'win64_msvc2019_arm64'
            modules: 'qtconnectivity qthttpserver qtmultimedia qtnetworkauth qtremoteobjects qtscxml'
            tools: 'tools_ninja'
        #
        # Install NSIS
        #
        - name: Install NSIS
          run: |
            Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
            scoop bucket add extras
            scoop install nsis

        #
        # Compile application
        #
        - name: Compile
          run: |
            make release

        #
        # Copy Qt DLLs, compiler runtime & application icon
        #
        - name: Deploy
          run: |
            make install DESTDIR=release
            windeployqt --dir= release\bin\ --compiler-runtime

        #
        # Create NSIS installer
        #
        - name: Make NSIS installer
          run: |
            move BANKING_SYSTEM deploy\windows\nsis\
            cd deploy\windows\nsis
            makensis /X"SetCompressor /FINAL lzma" setup.nsi
            ren *.exe Banking_System_Client-1.0.0-Windows.exe

        - name: Upload NSIS installer
          uses: actions/upload-artifact@v2
          with:
            name: Banking_System_Client-1.0.0-Windows.exe
            path: deploy/windows/nsis/Banking_System_Client-1.0.0-Windows.exe
